apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpassword"
        - name: MYSQL_DATABASE
          value: "truckbites"
        - name: MYSQL_USER
          value: "truckbites_user"
        - name: MYSQL_PASSWORD
          value: "truckbites_password"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi
spec:
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      initContainers:
        # Run EF migrations
        - name: ef-migrations
          image: truckbites-ef-migrations:latest
          imagePullPolicy: Never
          env:
            # For local dev, we use root, but in production we should use a user with least privileges
            - name: ConnectionStrings__DefaultConnection
              value: "Server=mysql;Database=truckbites;User=root;Password=rootpassword;"
      containers:
      - name: webapi
        image: truckbites-webapi:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        # Connection string points to the service name "mysql" defined above
        - name: ConnectionStrings__DefaultConnection
          value: "Server=mysql;Database=truckbites;User=truckbites_user;Password=truckbites_password;"
        - name: JwtSettings__Issuer
          value: "https://truckbites.eleven95.co"
        - name: JwtSettings__Audience
          value: "https://truckbites.eleven95.co"
        - name: JwtSettings__SecretKey
          value: "9D368479-BD44-4FB4-87CA-7916F4A81B60"
---
apiVersion: v1
kind: Service
metadata:
  name: webapi
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: webapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: truckbites-webapp:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        # Points to the internal K8s DNS name for the webapi service
        - name: Api__BaseUrl
          value: "http://webapi:8080/"
        - name: ReverseProxy__Clusters__external-api__Destinations__destination1__Address
          value: "http://webapi:8080/"
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: webapp
