apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin:latest
          env:
            - name: PMA_HOST
              value: "mysql"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  type: LoadBalancer
  ports:
    - port: 8082
      targetPort: 80
  selector:
    app: phpmyadmin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-webapi
spec:
  selector:
    matchLabels:
      app: customer-webapi
  template:
    metadata:
      labels:
        app: customer-webapi
    spec:
      initContainers:
        # Run EF migrations
        - name: ef-migrations
          image: truckbites-ef-migrations:latest
          imagePullPolicy: Never
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_ROOT_CONNECTION_STRING
      containers:
        - name: customer-webapi
          image: truckbites-customer-webapi:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_APP_CONNECTION_STRING
            - name: JwtSettings__Authority
              valueFrom:
                secretKeyRef:
                  name: customer-auth0-secret
                  key: CUSTOMER_WEBAPI_JWT_SETTINGS_AUTHORITY
            - name: JwtSettings__Audience
              valueFrom:
                secretKeyRef:
                  name: customer-auth0-secret
                  key: CUSTOMER_WEBAPI_JWT_SETTINGS_AUDIENCE
---
apiVersion: v1
kind: Service
metadata:
  name: customer-webapi
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: customer-webapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vendor-webapi
spec:
  selector:
    matchLabels:
      app: vendor-webapi
  template:
    metadata:
      labels:
        app: vendor-webapi
    spec:
      initContainers:
        # Run EF migrations
        - name: ef-migrations
          image: truckbites-ef-migrations:latest
          imagePullPolicy: Never
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_ROOT_CONNECTION_STRING
      containers:
        - name: vendor-webapi
          image: truckbites-vendor-webapi:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_APP_CONNECTION_STRING
            - name: JwtSettings__Authority
              valueFrom:
                secretKeyRef:
                  name: vendor-auth0-secret
                  key: VENDOR_WEBAPI_JWT_SETTINGS_AUTHORITY
            - name: JwtSettings__Audience
              valueFrom:
                secretKeyRef:
                  name: vendor-auth0-secret
                  key: VENDOR_WEBAPI_JWT_SETTINGS_AUDIENCE
---
apiVersion: v1
kind: Service
metadata:
  name: vendor-webapi
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: vendor-webapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-webapp
spec:
  selector:
    matchLabels:
      app: customer-webapp
  template:
    metadata:
      labels:
        app: customer-webapp
    spec:
      containers:
        - name: customer-webapp
          image: truckbites-customer-webapp:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: Api__BaseUrl
              value: "http://customer-webapi:8080/"
            - name: ReverseProxy__Clusters__external-api__Destinations__destination1__Address
              value: "http://customer-webapi:8080/"
            - name: Auth0__Domain
              valueFrom:
                secretKeyRef:
                  name: customer-auth0-secret
                  key: CUSTOMER_WEBAPP_AUTH0_DOMAIN
            - name: Auth0__ClientId
              valueFrom:
                secretKeyRef:
                  name: customer-auth0-secret
                  key: CUSTOMER_WEBAPP_AUTH0_CLIENT_ID
            - name: Auth0__Audience
              valueFrom:
                secretKeyRef:
                  name: customer-auth0-secret
                  key: CUSTOMER_WEBAPP_AUTH0_AUDIENCE
            - name: Auth0__ClientSecret
              valueFrom:
                secretKeyRef:
                  name: customer-auth0-secret
                  key: CUSTOMER_WEBAPP_AUTH0_CLIENT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: customer-webapp
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: customer-webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vendor-webapp
spec:
  selector:
    matchLabels:
      app: vendor-webapp
  template:
    metadata:
      labels:
        app: vendor-webapp
    spec:
      containers:
        - name: vendor-webapp
          image: truckbites-vendor-webapp:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: Api__BaseUrl
              value: "http://vendor-webapi:8080/"
            - name: ReverseProxy__Clusters__external-api__Destinations__destination1__Address
              value: "http://vendor-webapi:8080/"
            - name: Auth0__Domain
              valueFrom:
                secretKeyRef:
                  name: vendor-auth0-secret
                  key: VENDOR_WEBAPP_AUTH0_DOMAIN
            - name: Auth0__ClientId
              valueFrom:
                secretKeyRef:
                  name: vendor-auth0-secret
                  key: VENDOR_WEBAPP_AUTH0_CLIENT_ID
            - name: Auth0__Audience
              valueFrom:
                secretKeyRef:
                  name: vendor-auth0-secret
                  key: VENDOR_WEBAPP_AUTH0_AUDIENCE
            - name: Auth0__ClientSecret
              valueFrom:
                secretKeyRef:
                  name: vendor-auth0-secret
                  key: VENDOR_WEBAPP_AUTH0_CLIENT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: vendor-webapp
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8080
  selector:
    app: vendor-webapp
