// <auto-generated />
using System;
using Eleven95.TruckBites.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eleven95.TruckBites.EF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251126211343_FoodTrucks_Removed_Name")]
    partial class FoodTrucks_Removed_Name
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Eleven95.TruckBites.Data.Models.FoodTruck", b =>
                {
                    b.Property<long>("FoodTruckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("FoodTruckId");

                    b.ToTable("FoodTrucks");
                });
#pragma warning restore 612, 618
        }
    }
}
