// <auto-generated />
using System;
using Eleven95.TruckBites.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eleven95.TruckBites.EF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251126233240_Added_FoodTruckMenuItem")]
    partial class Added_FoodTruckMenuItem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Eleven95.TruckBites.Data.Models.FoodTruck", b =>
                {
                    b.Property<long>("FoodTruckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("FoodTruckId");

                    b.ToTable("FoodTrucks");
                });

            modelBuilder.Entity("Eleven95.TruckBites.Data.Models.FoodTruckMenuItem", b =>
                {
                    b.Property<long>("FoodTruckMenuItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("FoodTruckId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsSoldOut")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("FoodTruckMenuItemId");

                    b.HasIndex("FoodTruckId");

                    b.ToTable("FoodTruckMenuItems");
                });

            modelBuilder.Entity("Eleven95.TruckBites.Data.Models.FoodTruckMenuItem", b =>
                {
                    b.HasOne("Eleven95.TruckBites.Data.Models.FoodTruck", null)
                        .WithMany("MenuItems")
                        .HasForeignKey("FoodTruckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eleven95.TruckBites.Data.Models.FoodTruck", b =>
                {
                    b.Navigation("MenuItems");
                });
#pragma warning restore 612, 618
        }
    }
}
